### ISSUE TITLE
Cannot join WeChat group

### ISSUE THREAD

**Issue by tengpeng** [WeBankFinTech/WeDataSphere#1]
I tried to scan the QR code but I cannot join the WeChat group because the no. of users > 100, and I can only join by invitations.

**Comment by wushengyeyouya** [comment]
please add me wechat: 18682463060

**Comment by tengpeng** [comment]
I have tried to add your WeChat but it says "The user does not exist". Is
the no. correct? Is there a permission error? Thanks.

**Comment by wushengyeyouya** [comment]
wushengyeyy, please try again.
