### ISSUE TITLE
Missing Components 

### ISSUE THREAD

**Issue by tengpeng** [WeBankFinTech/WeDataSphere#2]
I have tried to deploy WeDataShpere on my local server, but it seems many components, including 工作流，看板系统，EasyIDE. I have searched the entire project and failed to find such components. Check out this screenshot.

![image](https://user-images.githubusercontent.com/2724786/62048546-bf14b580-b23f-11e9-8b58-facab6347368.png)

**Comment by wushengyeyouya** [comment]
We will gradually open up these modules, please pay attention to our open source plan. If you have any other questions, please go to Scriptis repo to give us an issue, thank you!
