### ISSUE TITLE
翻译领取：

### ISSUE THREAD

**Issue by yangli-os** [WeBankFinTech/WeDataSphere#34]
下面是需要翻译的文章链接，领取翻译任务的小伙伴可以在链接后@自己，即认为该翻译任务已被领取。该翻译任务结束后，可以将该翻译任务的链接转移到已完成/Done中，并附上翻译后发布的文章链接。
https://zhuanlan.zhihu.com/p/509745572 @李扬

**Comment by xingyx** [comment]
您的邮件已经顺利到达我的邮箱中了~  谢谢您的邮件
