### ISSUE TITLE
【待认领】Meetup 03期活动回顾推文

### ISSUE THREAD

**Issue by Andywli** [WeBankFinTech/WeDataSphere#35]
活动详情：[《Meetup预告：Linkis新版本介绍以及DSS的应用实践》](https://mp.weixin.qq.com/s/jKPidHqP-NmCQuUPFmbniA)

【需求描述】
撰写本期活动回顾的推文，文章内容需要包含以下关键要素：
1、活动主题、时间、内容简要；
2、讲师的姓名、公司、职位、分享的主题；
3、每个主题的精华概要+材料截图；

【活动素材】
1、活动视频；
2、两位讲师的PPT；
链接: https://pan.baidu.com/s/1ocrDERTFNrY64Ckk4vUboQ?pwd=pixy 提取码: pixy

【参考资料】
1、[Meetup 02期回顾：Qualitis、Prophecis、DSS、Schedulis四大组件介绍](https://mp.weixin.qq.com/s/mi-wXfq9fOvzy_qcBd5LcA)
2、[活动回顾 | Linkis新版本的特性介绍以及使用实践](https://mp.weixin.qq.com/s/YIOY0xTqEnGtTtp2AznWnA)
3、[【活动回顾】这场开源大数据盛会，我们把所有演讲内容浓缩成10分钟精华](https://mp.weixin.qq.com/s/VdsMlXaIm-JJp6ZqsiWpGQ)

【任务Tips】
1、使用飞书妙记，把视频中老师的语音转化为文字；
2、摘录老师分享的重要内容或者经典内容，再配图PPT；

完成时间：6月15日（内容提交给Andy验收）
推文时间：6月17日

如有任何疑问，请联系Andy

**Comment by yangli-os** [comment]
已认领
