### ISSUE TITLE
翻译任务认领

### ISSUE THREAD

**Issue by yangli-os** [WeBankFinTech/WeDataSphere#37]
【Linkis 开发群内容翻译】
概述：开发群讨论内容翻译，发布在邮件中，任务时限一般为3-7天

【Linkis 文章翻译】
概述：公众号上发布的文章翻译，任务时限一般为7-14天

示例/SOP：https://docs.qq.com/doc/DQXJ1am5xdkRGb2lu

查看以及领取任务：https://docs.qq.com/doc/DYkxMbVpKT3FsUmFX

**Comment by xingyx** [comment]
您的邮件已经顺利到达我的邮箱中了~  谢谢您的邮件
