### ISSUE TITLE
scriptis编写shell脚本会忽略行如--arg的命令行参数

### ISSUE THREAD

**Issue by hankai520** [WeBankFinTech/WeDataSphere#7]
尝试通过shell执行sqoop导入命令时，执行形如 "sqoop import --hive-import..." 的命令行，查看日志，显示只执行了 sqoop import，语法不正确。该行为与shell注释的惯例不同。

**Comment by wushengyeyouya** [comment]
Please open this issue in DataSphere Studio project, Thanks very much!
